theme: jekyll-theme-slate
title: Waterloo Region Votes
description: Information About the 2022 Municipal Election
show_downloads: false
plugins:
  - jekyll-sitemap

defaults:
  -
   values:
     layout: "default"

empty-array: []

teaser_limit_events_multi_candidate: 7
teaser_limit_events_specific: 2
teaser_limit_events_generic: 5
teaser_limit_news: 5
teaser_limit_surveys: 5

google_calendar_id: kic9nk7sfv786tcrmfujlc46jg@group.calendar.google.com

google_calendar_timezone: America/Toronto

google_analytics: UA-102439664-2

contact_email: "civictechwr.wrvotes@gmail.com"

# events_newsletter: "https://off-topic.kwlug.org/mailman/listinfo/waterlooregionvotes-events_off-topic.kwlug.org"

election_over: false

# This should be a number strictly greater than the number of votes
# received by any candidate in any race. 
big_number: 10000000
